version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_blog
      - MYSQL_USER=root
    ports: 
      - 3306:3306
  blog:
    image: blog_basti_uebung:0.0.1-SNAPSHOT
    ports: 
      - 8282:8282
    environment: 
      - MYSQL_HOST=mysql
    links:
      - mysql
    depends_on:
      - mysql